export const reactTopics = [
  {
    category: "React Basics",
    topics: [
      "Introduction to React Patterns",
      "What is React",
      "Functional Components",
      "State Colocation",
      "Controlled vs Uncontrolled Components",
      "Context API",
    ],
  },
  {
    category: "React Patterns",
    topics: [
      "Higher-Order Components (HOC)",
      "Render Props",
      "Compound Components",
      "Provider Pattern",
      "Layout Component Pattern",
      "Hooks Factory",
      "State Reducer Pattern",
      "Props Getters",
      "Slot Pattern",
      "Container-Presenter Pattern",
      "Error Boundary Pattern",
      "Suspense Pattern",
      "Code Splitting",
      "Portal Pattern",
      "Render Optimization",
      "Forward Ref Pattern",
      "Immutable State Updates",
      "Summary & Best Practices",
    ],
  },
  {
    category: "Hooks & Custom Logic",
    topics: ["Custom Hooks", "Reducer Pattern"],
  },
];
